### ISSUE TITLE
suckher man....

### ISSUE THREAD

**Issue by oijwoijifaojsidjg** [majorsopa/make-husks-drop-sand#1]

**Comment by oijwoijifaojsidjg** [comment]
nice viruaz
reported to staf on rob blox

**Comment by oijwoijifaojsidjg** [comment]
settings.gradle vrisuz....

VIrus:
pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

**Comment by oijwoijifaojsidjg** [comment]
pooper man

**Comment by majorsopa** [comment]
WTf how

**Comment by cope3503** [comment]
STP OSTPOP OSTPOP OSPT
ho to re  open

**Comment by majorsopa** [comment]
You're mom

**Comment by cope3503** [comment]
fucker propagnada. ..
